<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DiffEngine" Version="20.7.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.184" />
    <PackageVersion Include="TUnit" Version="1.73.5" />
    <PackageVersion Include="Verify" Version="33.3.2" />
    <PackageVersion Include="Verify.TUnit" Version="33.3.2" />
  </ItemGroup>
</Project>
