global using System;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Reflection.Metadata;
global using System.Reflection.PortableExecutable;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Loader;
global using System.Security.Cryptography;
global using System.Text;
global using System.Threading.Tasks;
global using System.Xml.Linq;
global using Microsoft.Build.Framework;
global using TaskItem = Microsoft.Build.Utilities.TaskItem;
global using Squash;
global using TUnit.Core;
global using static VerifyTUnit.Verifier;
